"""empty message

Revision ID: a85b8f5ea238
Revises: 05bb9dcceee9
Create Date: 2018-12-22 12:42:47.114072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85b8f5ea238'
down_revision = '05bb9dcceee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'project', ['name'], unique=True)
    # ### end Alembic commands ###
