"""empty message

Revision ID: ebb7a1ff216e
Revises: a85b8f5ea238
Create Date: 2018-12-29 22:41:58.391061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb7a1ff216e'
down_revision = 'a85b8f5ea238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_request', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_request', 'title')
    # ### end Alembic commands ###
